// AUTO-GENERATED by scripts/gen-maps (do not edit by hand).
// Collision grids + placement transforms baked from the map GLBs.
import type { MapGeo } from "./maps";

export const MAP_GEO: Record<string, MapGeo> = {
  "backrooms": {
    "id": "backrooms",
    "scale": 0.9692,
    "offsetY": 0,
    "bounds": {
      "minX": -18.29,
      "maxX": 18.29,
      "minZ": -31,
      "maxZ": 31
    },
    "spawn": {
      "x": 0,
      "z": 0.45,
      "radius": 11.6
    },
    "grid": {
      "originX": -19.35,
      "originZ": -32.4,
      "cols": 43,
      "rows": 72,
      "cell": 0.9,
      "bits": "//////8PAAAAAGAAAEAAAAMAAAIAGAAAEADAAACAAAAGAAAEADAAACAAgAEAAAEADAAACABgAABAAAADAAACABgAABAAwAAAgAAABgAABAAwAAAgAIABAAABAAwAAAgAYAAAQAAAAwAAAgAYAAAQAMAAAIAAAAYAAAQAMAAAIACAAQAAAQAMAAAIAGAAAEAAAAMAAAIAGAAAEADAAACAAAAGAA4EADAAUCAAgAGAgwEADAAADABgAOBgAAADAAUDABgAOBgAwAAAwAAABgAABgAwAAAwAIABAIABAAwAAAwAYAAAYAAAAwAAAAAYAAAAAMAAAAAAAAYAAAAAMAAAAACA//////8PAAAAAGAAAAAAAAMAAAAAGAAAAADAAAAAAAAGAAAAADAAAAAAgAEAAAAADAAAAABgAAAAAAADAAAAABgAAAAAwAAAAAAABgAAAAAwAAAAAIABAAAAAAwAAAAAYAAAAAAAAwAAAAAYAAAAAMAAAAAAAAYAAAAA8P//////"
    }
  },
  "sewer": {
    "id": "sewer",
    "scale": 0.44381,
    "offsetY": 1.11,
    "bounds": {
      "minX": -31,
      "maxX": 31,
      "minZ": -18.33,
      "maxZ": 18.33
    },
    "spawn": {
      "x": 0.45,
      "z": 0,
      "radius": 11.6
    },
    "grid": {
      "originX": -32.4,
      "originZ": -19.35,
      "cols": 72,
      "rows": 43,
      "cell": 0.9,
      "bits": "////////////AQAAAAAAAADwAQAAAAAAAADwAQAAAAAAAADwAQAAAAAAAADwAQAAAAAAAID/AQAAAAAAAOD/AQAAAAAAALj/AQAAAAAAAHjwAQAAAAAAABbwAQAAAAAAAA7wAQAAAAAAAAfwAQAAAAAAAAeAAQAAAAAAAAeAHwAAAAAAgAOAHQAAAAAAgAOAHQAAAAAAgAOAHQAAAAAAgAOAHQAAAAAAgAOAHQAAAAAAgAOAHQAAAAAAgAOAOQAAAAAAgAOAeQAAAAAAgAOAcQAAAPj///uA4QMADPD//5+Awf////////uDgf///x8GMJODAfz//58O8pODAQAADPj///+AAQAADMAMRweAAQAADMAMRx+AAQAADMAMRxuAAQAADMAARx+AAQAAHMAARwGAAQAADMAARwGAAQAAH8AARwGAAQAAP8AARwGAAQD+X8AARwGAAQCAc8AAxwGAAQCAcwAAAACAAQD+fwAAAACAAQAALwAAAACA////////////"
    }
  }
};
